# Generated by Django 5.1.6 on 2025-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
